export const authSelectors = { 

    emailInput: '[data-testid="email-input"]',
    nombreInput: '[data-testid="nombre-input"]',
    passwordInput: '[data-testid="password-input"]',
    submitButton: '[data-testid="submit-button"]',
    registerButton: '[data-testid="register-button"]',
    contactName: '[data-testid="contact-name"]',
    contactItem: '[data-testid="contact-item"]',
    searchInput: '[data-testid="search-contact"]',
    chatBubbleContact: '[data-testid="chat-bubble-contact"]',
    chatBubbleUser: '[data-testid="chat-bubble-user"]',
    lupaButton: '[data-testid="search-message-button"]',
    searchMessagesInput: '[data-testid="search-messages"]', 
    addContactButton: '[data-testid="add-contact-button"]',
    menuOptions: 'button:contains("⋮")',
    cleanLocal: 'button:contains("Limpiar chat para mí")',
    cleanGlobal: 'button:contains("Borrar historial definitivo")',
    messageInput: '[data-testid="message-input"]',
    sendMessageButton: '[data-testid="send-message-button"]',
    sidebarToggle: '[data-testid="sidebar-toggle"]',
    logoutButton: '[data-testid="logout-button"]',
    addContactInput: '[data-testid="add-contact-input"]',
    sendInvitationButton: '[data-testid="send-invitation-button"]',
    acceptInvitationButton: '[data-testid="accept-invitation-button"]',
}